### ISSUE TITLE
Percentage semantic type

### ISSUE THREAD

**Issue by samubura** [Azure/opendigitaltwins-dtdl#122] opened 2021-10-10 17:19 UTC
I feel that having a percentage semantic type would be beneficial for a lot of implementations. 
It should be fairly easy to add and can protect integer fields from being misinterpreted when doing computation.
(e.g. a percentage should always be >=0 and <=100)

**Comment by rido-min** [comment] 2023-01-27 16:04
closing as a dupe of #140

**Closed as completed by rido-min** 2023-01-27 16:04 UTC
